### ISSUE TITLE
Work on the buldge for the `trace_width` with large value

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/pcb-viewer#36]
This is how it looks for the dramatic 20 width. Make the starting point of the edges a bit more narrow and then it should buldge in between
              
<img width="957" alt="Screenshot 2024-08-16 at 2 20 26 AM" src="https://github.com/user-attachments/assets/2831bf12-6cac-4cef-8436-2d5947c2d39a">

_Originally posted by @imrishabh18 in https://github.com/tscircuit/pcb-viewer/issues/35#issuecomment-2292214892_

**Comment by seveibar** [comment]
hehe ok something was a tiny bit off, well we're a bit closer now at least.

**Comment by imrishabh18** [comment]
Which line? I have three route endpoints and all are there

**Comment by seveibar** [comment]
![image](https://github.com/user-attachments/assets/e0f61c00-3d49-4641-b9cf-1b193d6aa34c)

I think the first line is missing

**Comment by imrishabh18** [comment]
The width is off, I think because the default value of the thickness of the route is 1 (when no width is mentioned)

**Comment by seveibar** [comment]
The default has a couple places where it can come from- the Board (from <board /> should set the default in builder.

the shape isnt right though, it should narrow at the point

![image](https://github.com/user-attachments/assets/d1bd4802-ea1e-4b8a-b245-856f54eb0e3c)

**Comment by seveibar** [comment]
There should be a default defined in the builder but i think its supposed to be 0.05 (but we shouldn't hard code that anywhere except as the board/build context default)

**Comment by seveibar** [comment]
![image](https://github.com/user-attachments/assets/ddf1b5b8-a37c-4bf4-91d3-245e47ae5724)

Another example of how the widths should change
