### ISSUE TITLE
.right and .left selectors are incorrect

### ISSUE THREAD

**Issue by ShiboSoftwareDev** [tscircuit/pcb-viewer#66]
![image](https://github.com/user-attachments/assets/5b38d7b2-133a-426e-967b-8eecda063a40)

![image](https://github.com/user-attachments/assets/f818ad74-9cfb-40aa-a26d-5724fbd47322)

found this in /cli repo resistor example

**Comment by Abse2001** [comment]
It wasn't an issue, it was changed from right and left to .pin1 .pin2.

![Image](https://github.com/user-attachments/assets/e626cf54-2769-4bb5-8830-670ce17d43d5)
