### ISSUE TITLE
Error message is on top of the `Edit Trace` button

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/pcb-viewer#80]
The `Edit trace` button becomes un-clickable, as the error message is on top of it.

![Image](https://github.com/user-attachments/assets/93bd9937-ead7-4b3f-aab1-46c808e7cbd4)

**Comment by Abse2001** [comment]
closed ![Image](https://github.com/user-attachments/assets/3a2630cf-5622-41e2-9ddb-86c312af8bed)
